import '../../data/models/common/country_code/country_code.dart';
import '../localization/strings/country_strings.dart';
import '../localization/strings/nationality_strings.dart';

/// Flag images + translatable name helpers for [CountryCode].
///
/// Usage:
/// ```dart
/// Text(country.translatedName)       // Localized name
/// CachedNetworkImage(imageUrl: country.flagImageUrl)
/// Image.network(country.flagImageUrl) // Works everywhere
/// country.flagEmoji                   // Emoji fallback for offline
/// ```
extension CountryCodeHelpers on CountryCode {
  // ─── Translatable name ─────────────────────────────────────

  /// Localized country name via translation keys.
  /// Falls back to the raw [name] field if no translation key exists.
  String get translatedName => _countryNameFor(code) ?? name ?? '';

  /// Localized nationality demonym — "Jordanian" / "أردني". Falls back
  /// to [translatedName] when no key exists.
  String get translatedNationality => _nationalityFor(code) ?? translatedName;

  // ─── Flag images via flagcdn.com CDN ───────────────────────

  /// Flag PNG image URL (32x24).
  String get flagImageUrl =>
      'https://flagcdn.com/32x24/${code.toLowerCase()}.png';

  /// Flag PNG 2x image URL (64x48) for high-DPI screens.
  String get flagImageUrl2x =>
      'https://flagcdn.com/64x48/${code.toLowerCase()}.png';

  /// Flag PNG 3x image URL (96x72) for highest-DPI screens.
  String get flagImageUrl3x =>
      'https://flagcdn.com/96x72/${code.toLowerCase()}.png';

  /// Flag SVG URL — best quality, scalable.
  String get flagSvgUrl => 'https://flagcdn.com/${code.toLowerCase()}.svg';

  /// Flag WebP image URL (32x24) — smaller file size than PNG.
  String get flagWebpUrl =>
      'https://flagcdn.com/32x24/${code.toLowerCase()}.webp';

  /// Emoji flag (from the [flag] field). Use as fallback when offline.
  String get flagEmoji => flag ?? '';
}

// ─── Country code → localized display name ────────────────────
//
// Resolved per-call (not a `final` map) so locale changes re-render
// without a restart. `CountryStrings.*` are getters backed by the ARB
// + remote overlay.

String? _countryNameFor(String? code) => switch (code) {
  'JO' => CountryStrings.jordan,
  'US' => CountryStrings.unitedStates,
  'GB' => CountryStrings.unitedKingdom,
  'SA' => CountryStrings.saudiArabia,
  'AE' => CountryStrings.unitedArabEmirates,
  'KW' => CountryStrings.kuwait,
  'QA' => CountryStrings.qatar,
  'BH' => CountryStrings.bahrain,
  'OM' => CountryStrings.oman,
  'EG' => CountryStrings.egypt,
  'LB' => CountryStrings.lebanon,
  'SY' => CountryStrings.syria,
  'IQ' => CountryStrings.iraq,
  'PS' => CountryStrings.palestine,
  'YE' => CountryStrings.yemen,
  'LY' => CountryStrings.libya,
  'TN' => CountryStrings.tunisia,
  'DZ' => CountryStrings.algeria,
  'MA' => CountryStrings.morocco,
  'SD' => CountryStrings.sudan,
  'TR' => CountryStrings.turkey,
  'IR' => CountryStrings.iran,
  'PK' => CountryStrings.pakistan,
  'AF' => CountryStrings.afghanistan,
  'IN' => CountryStrings.india,
  'BD' => CountryStrings.bangladesh,
  'LK' => CountryStrings.sriLanka,
  'NP' => CountryStrings.nepal,
  'MM' => CountryStrings.myanmar,
  'TH' => CountryStrings.thailand,
  'VN' => CountryStrings.vietnam,
  'KH' => CountryStrings.cambodia,
  'LA' => CountryStrings.laos,
  'MY' => CountryStrings.malaysia,
  'SG' => CountryStrings.singapore,
  'ID' => CountryStrings.indonesia,
  'PH' => CountryStrings.philippines,
  'CN' => CountryStrings.china,
  'JP' => CountryStrings.japan,
  'KR' => CountryStrings.southKorea,
  'KP' => CountryStrings.northKorea,
  'MN' => CountryStrings.mongolia,
  'TW' => CountryStrings.taiwan,
  'HK' => CountryStrings.hongKong,
  'MO' => CountryStrings.macau,
  'CA' => CountryStrings.canada,
  'MX' => CountryStrings.mexico,
  'BR' => CountryStrings.brazil,
  'AR' => CountryStrings.argentina,
  'CL' => CountryStrings.chile,
  'PE' => CountryStrings.peru,
  'CO' => CountryStrings.colombia,
  'VE' => CountryStrings.venezuela,
  'EC' => CountryStrings.ecuador,
  'BO' => CountryStrings.bolivia,
  'PY' => CountryStrings.paraguay,
  'UY' => CountryStrings.uruguay,
  'GY' => CountryStrings.guyana,
  'SR' => CountryStrings.suriname,
  'GF' => CountryStrings.frenchGuiana,
  'DE' => CountryStrings.germany,
  'FR' => CountryStrings.france,
  'IT' => CountryStrings.italy,
  'ES' => CountryStrings.spain,
  'PT' => CountryStrings.portugal,
  'NL' => CountryStrings.netherlands,
  'BE' => CountryStrings.belgium,
  'CH' => CountryStrings.switzerland,
  'AT' => CountryStrings.austria,
  'SE' => CountryStrings.sweden,
  'NO' => CountryStrings.norway,
  'DK' => CountryStrings.denmark,
  'FI' => CountryStrings.finland,
  'IS' => CountryStrings.iceland,
  'PL' => CountryStrings.poland,
  'CZ' => CountryStrings.czechRepublic,
  'SK' => CountryStrings.slovakia,
  'HU' => CountryStrings.hungary,
  'RO' => CountryStrings.romania,
  'BG' => CountryStrings.bulgaria,
  'HR' => CountryStrings.croatia,
  'SI' => CountryStrings.slovenia,
  'RS' => CountryStrings.serbia,
  'ME' => CountryStrings.montenegro,
  'BA' => CountryStrings.bosniaAndHerzegovina,
  'MK' => CountryStrings.northMacedonia,
  'AL' => CountryStrings.albania,
  'GR' => CountryStrings.greece,
  'CY' => CountryStrings.cyprus,
  'MT' => CountryStrings.malta,
  'IE' => CountryStrings.ireland,
  'LU' => CountryStrings.luxembourg,
  'MC' => CountryStrings.monaco,
  'LI' => CountryStrings.liechtenstein,
  'SM' => CountryStrings.sanMarino,
  'VA' => CountryStrings.vaticanCity,
  'AD' => CountryStrings.andorra,
  'RU' => CountryStrings.russia,
  'UA' => CountryStrings.ukraine,
  'BY' => CountryStrings.belarus,
  'MD' => CountryStrings.moldova,
  'EE' => CountryStrings.estonia,
  'LV' => CountryStrings.latvia,
  'LT' => CountryStrings.lithuania,
  'GE' => CountryStrings.georgia,
  'AM' => CountryStrings.armenia,
  'AZ' => CountryStrings.azerbaijan,
  'KZ' => CountryStrings.kazakhstan,
  'UZ' => CountryStrings.uzbekistan,
  'KG' => CountryStrings.kyrgyzstan,
  'TJ' => CountryStrings.tajikistan,
  'TM' => CountryStrings.turkmenistan,
  'AU' => CountryStrings.australia,
  'NZ' => CountryStrings.newZealand,
  'ZA' => CountryStrings.southAfrica,
  'NG' => CountryStrings.nigeria,
  'KE' => CountryStrings.kenya,
  'GH' => CountryStrings.ghana,
  'ET' => CountryStrings.ethiopia,
  'ZZ' => CountryStrings.unknown,
  'AO' => CountryStrings.angola,
  'BF' => CountryStrings.burkinaFaso,
  'BJ' => CountryStrings.benin,
  'BW' => CountryStrings.botswana,
  'CD' => CountryStrings.democraticRepublicOfTheCongo,
  'CF' => CountryStrings.centralAfricanRepublic,
  'CG' => CountryStrings.congo,
  'CI' => CountryStrings.coteDIvoire,
  'CM' => CountryStrings.cameroon,
  'CV' => CountryStrings.capeVerde,
  'DJ' => CountryStrings.djibouti,
  'EH' => CountryStrings.westernSahara,
  'ER' => CountryStrings.eritrea,
  'FJ' => CountryStrings.fiji,
  'FM' => CountryStrings.micronesia,
  'GA' => CountryStrings.gabon,
  'GM' => CountryStrings.gambia,
  'GN' => CountryStrings.guinea,
  'GQ' => CountryStrings.equatorialGuinea,
  'GW' => CountryStrings.guineaBissau,
  'KI' => CountryStrings.kiribati,
  'KM' => CountryStrings.comoros,
  'LR' => CountryStrings.liberia,
  'LS' => CountryStrings.lesotho,
  'MG' => CountryStrings.madagascar,
  'MH' => CountryStrings.marshallIslands,
  'ML' => CountryStrings.mali,
  'MR' => CountryStrings.mauritania,
  'MU' => CountryStrings.mauritius,
  'MW' => CountryStrings.malawi,
  'MZ' => CountryStrings.mozambique,
  'NA' => CountryStrings.namibia,
  'NC' => CountryStrings.newCaledonia,
  'NE' => CountryStrings.niger,
  'NR' => CountryStrings.nauru,
  'PF' => CountryStrings.frenchPolynesia,
  'PG' => CountryStrings.papuaNewGuinea,
  'PW' => CountryStrings.palau,
  'SB' => CountryStrings.solomonIslands,
  'SC' => CountryStrings.seychelles,
  'SL' => CountryStrings.sierraLeone,
  'SN' => CountryStrings.senegal,
  'SO' => CountryStrings.somalia,
  'ST' => CountryStrings.saoTomeAndPrincipe,
  'SZ' => CountryStrings.eswatini,
  'TD' => CountryStrings.chad,
  'TG' => CountryStrings.togo,
  'TO' => CountryStrings.tonga,
  'TV' => CountryStrings.tuvalu,
  'TZ' => CountryStrings.tanzania,
  'UG' => CountryStrings.uganda,
  'VU' => CountryStrings.vanuatu,
  'WS' => CountryStrings.samoa,
  'ZM' => CountryStrings.zambia,
  'ZW' => CountryStrings.zimbabwe,
  _ => null,
};

// Resolved per-call for the same live-locale reason as
// `_countryNameFor` above.
String? _nationalityFor(String? code) => switch (code) {
  'JO' => NationalityStrings.jordan,
  'US' => NationalityStrings.unitedStates,
  'GB' => NationalityStrings.unitedKingdom,
  'SA' => NationalityStrings.saudiArabia,
  'AE' => NationalityStrings.unitedArabEmirates,
  'KW' => NationalityStrings.kuwait,
  'QA' => NationalityStrings.qatar,
  'BH' => NationalityStrings.bahrain,
  'OM' => NationalityStrings.oman,
  'EG' => NationalityStrings.egypt,
  'LB' => NationalityStrings.lebanon,
  'SY' => NationalityStrings.syria,
  'IQ' => NationalityStrings.iraq,
  'PS' => NationalityStrings.palestine,
  'YE' => NationalityStrings.yemen,
  'LY' => NationalityStrings.libya,
  'TN' => NationalityStrings.tunisia,
  'DZ' => NationalityStrings.algeria,
  'MA' => NationalityStrings.morocco,
  'SD' => NationalityStrings.sudan,
  'TR' => NationalityStrings.turkey,
  'IR' => NationalityStrings.iran,
  'PK' => NationalityStrings.pakistan,
  'AF' => NationalityStrings.afghanistan,
  'IN' => NationalityStrings.india,
  'BD' => NationalityStrings.bangladesh,
  'LK' => NationalityStrings.sriLanka,
  'NP' => NationalityStrings.nepal,
  'MM' => NationalityStrings.myanmar,
  'TH' => NationalityStrings.thailand,
  'VN' => NationalityStrings.vietnam,
  'KH' => NationalityStrings.cambodia,
  'LA' => NationalityStrings.laos,
  'MY' => NationalityStrings.malaysia,
  'SG' => NationalityStrings.singapore,
  'ID' => NationalityStrings.indonesia,
  'PH' => NationalityStrings.philippines,
  'CN' => NationalityStrings.china,
  'JP' => NationalityStrings.japan,
  'KR' => NationalityStrings.southKorea,
  'KP' => NationalityStrings.northKorea,
  'MN' => NationalityStrings.mongolia,
  'TW' => NationalityStrings.taiwan,
  'HK' => NationalityStrings.hongKong,
  'MO' => NationalityStrings.macau,
  'CA' => NationalityStrings.canada,
  'MX' => NationalityStrings.mexico,
  'BR' => NationalityStrings.brazil,
  'AR' => NationalityStrings.argentina,
  'CL' => NationalityStrings.chile,
  'PE' => NationalityStrings.peru,
  'CO' => NationalityStrings.colombia,
  'VE' => NationalityStrings.venezuela,
  'EC' => NationalityStrings.ecuador,
  'BO' => NationalityStrings.bolivia,
  'PY' => NationalityStrings.paraguay,
  'UY' => NationalityStrings.uruguay,
  'GY' => NationalityStrings.guyana,
  'SR' => NationalityStrings.suriname,
  'GF' => NationalityStrings.frenchGuiana,
  'DE' => NationalityStrings.germany,
  'FR' => NationalityStrings.france,
  'IT' => NationalityStrings.italy,
  'ES' => NationalityStrings.spain,
  'PT' => NationalityStrings.portugal,
  'NL' => NationalityStrings.netherlands,
  'BE' => NationalityStrings.belgium,
  'CH' => NationalityStrings.switzerland,
  'AT' => NationalityStrings.austria,
  'SE' => NationalityStrings.sweden,
  'NO' => NationalityStrings.norway,
  'DK' => NationalityStrings.denmark,
  'FI' => NationalityStrings.finland,
  'IS' => NationalityStrings.iceland,
  'PL' => NationalityStrings.poland,
  'CZ' => NationalityStrings.czechRepublic,
  'SK' => NationalityStrings.slovakia,
  'HU' => NationalityStrings.hungary,
  'RO' => NationalityStrings.romania,
  'BG' => NationalityStrings.bulgaria,
  'HR' => NationalityStrings.croatia,
  'SI' => NationalityStrings.slovenia,
  'RS' => NationalityStrings.serbia,
  'ME' => NationalityStrings.montenegro,
  'BA' => NationalityStrings.bosniaAndHerzegovina,
  'MK' => NationalityStrings.northMacedonia,
  'AL' => NationalityStrings.albania,
  'GR' => NationalityStrings.greece,
  'CY' => NationalityStrings.cyprus,
  'MT' => NationalityStrings.malta,
  'IE' => NationalityStrings.ireland,
  'LU' => NationalityStrings.luxembourg,
  'MC' => NationalityStrings.monaco,
  'LI' => NationalityStrings.liechtenstein,
  'SM' => NationalityStrings.sanMarino,
  'VA' => NationalityStrings.vaticanCity,
  'AD' => NationalityStrings.andorra,
  'RU' => NationalityStrings.russia,
  'UA' => NationalityStrings.ukraine,
  'BY' => NationalityStrings.belarus,
  'MD' => NationalityStrings.moldova,
  'EE' => NationalityStrings.estonia,
  'LV' => NationalityStrings.latvia,
  'LT' => NationalityStrings.lithuania,
  'GE' => NationalityStrings.georgia,
  'AM' => NationalityStrings.armenia,
  'AZ' => NationalityStrings.azerbaijan,
  'KZ' => NationalityStrings.kazakhstan,
  'UZ' => NationalityStrings.uzbekistan,
  'KG' => NationalityStrings.kyrgyzstan,
  'TJ' => NationalityStrings.tajikistan,
  'TM' => NationalityStrings.turkmenistan,
  'AU' => NationalityStrings.australia,
  'NZ' => NationalityStrings.newZealand,
  'ZA' => NationalityStrings.southAfrica,
  'NG' => NationalityStrings.nigeria,
  'KE' => NationalityStrings.kenya,
  'GH' => NationalityStrings.ghana,
  'ET' => NationalityStrings.ethiopia,
  'ZZ' => NationalityStrings.unknown,
  'AO' => NationalityStrings.angola,
  'BF' => NationalityStrings.burkinaFaso,
  'BJ' => NationalityStrings.benin,
  'BW' => NationalityStrings.botswana,
  'CD' => NationalityStrings.democraticRepublicOfTheCongo,
  'CF' => NationalityStrings.centralAfricanRepublic,
  'CG' => NationalityStrings.congo,
  'CI' => NationalityStrings.coteDIvoire,
  'CM' => NationalityStrings.cameroon,
  'CV' => NationalityStrings.capeVerde,
  'DJ' => NationalityStrings.djibouti,
  'EH' => NationalityStrings.westernSahara,
  'ER' => NationalityStrings.eritrea,
  'FJ' => NationalityStrings.fiji,
  'FM' => NationalityStrings.micronesia,
  'GA' => NationalityStrings.gabon,
  'GM' => NationalityStrings.gambia,
  'GN' => NationalityStrings.guinea,
  'GQ' => NationalityStrings.equatorialGuinea,
  'GW' => NationalityStrings.guineaBissau,
  'KI' => NationalityStrings.kiribati,
  'KM' => NationalityStrings.comoros,
  'LR' => NationalityStrings.liberia,
  'LS' => NationalityStrings.lesotho,
  'MG' => NationalityStrings.madagascar,
  'MH' => NationalityStrings.marshallIslands,
  'ML' => NationalityStrings.mali,
  'MR' => NationalityStrings.mauritania,
  'MU' => NationalityStrings.mauritius,
  'MW' => NationalityStrings.malawi,
  'MZ' => NationalityStrings.mozambique,
  'NA' => NationalityStrings.namibia,
  'NC' => NationalityStrings.newCaledonia,
  'NE' => NationalityStrings.niger,
  'NR' => NationalityStrings.nauru,
  'PF' => NationalityStrings.frenchPolynesia,
  'PG' => NationalityStrings.papuaNewGuinea,
  'PW' => NationalityStrings.palau,
  'SB' => NationalityStrings.solomonIslands,
  'SC' => NationalityStrings.seychelles,
  'SL' => NationalityStrings.sierraLeone,
  'SN' => NationalityStrings.senegal,
  'SO' => NationalityStrings.somalia,
  'ST' => NationalityStrings.saoTomeAndPrincipe,
  'SZ' => NationalityStrings.eswatini,
  'TD' => NationalityStrings.chad,
  'TG' => NationalityStrings.togo,
  'TO' => NationalityStrings.tonga,
  'TV' => NationalityStrings.tuvalu,
  'TZ' => NationalityStrings.tanzania,
  'UG' => NationalityStrings.uganda,
  'VU' => NationalityStrings.vanuatu,
  'WS' => NationalityStrings.samoa,
  'ZM' => NationalityStrings.zambia,
  'ZW' => NationalityStrings.zimbabwe,
  _ => null,
};
