// File generated by FlutterFire CLI.
//
// **TODO(adopter)**: This is a placeholder pointing at the dev Firebase
// project. Regenerate for the staging Firebase project:
//   flutterfire configure \
//     --project=<your-staging-firebase-project-id> \
//     --out=lib/firebase_options_staging.dart \
//     --ios-bundle-id=com.dottech.flutterBaseApp \
//     --android-package-name=com.dottech.terracotta
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWwn2rzLXNY8EJcVlScrfLAbdIL2b2s9A',
    appId: '1:201792782069:web:51ba499f85c28e80418fbc',
    messagingSenderId: '201792782069',
    projectId: 'flutter-base-app-209d4',
    authDomain: 'flutter-base-app-209d4.firebaseapp.com',
    storageBucket: 'flutter-base-app-209d4.firebasestorage.app',
    measurementId: 'G-3LX9W7D2W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxx_WaBJtuusP4lQNKY4QIsz36hWr3O60',
    appId: '1:201792782069:android:918edb84112651a5418fbc',
    messagingSenderId: '201792782069',
    projectId: 'flutter-base-app-209d4',
    storageBucket: 'flutter-base-app-209d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALwPERR-2otjDgS36CgtAAiF09SnHJ_30',
    appId: '1:201792782069:ios:01a314c27784c38a418fbc',
    messagingSenderId: '201792782069',
    projectId: 'flutter-base-app-209d4',
    storageBucket: 'flutter-base-app-209d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterBaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALwPERR-2otjDgS36CgtAAiF09SnHJ_30',
    appId: '1:201792782069:ios:01a314c27784c38a418fbc',
    messagingSenderId: '201792782069',
    projectId: 'flutter-base-app-209d4',
    storageBucket: 'flutter-base-app-209d4.firebasestorage.app',
    iosBundleId: 'com.example.flutterBaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWwn2rzLXNY8EJcVlScrfLAbdIL2b2s9A',
    appId: '1:201792782069:web:fcf553a8262fc9dd418fbc',
    messagingSenderId: '201792782069',
    projectId: 'flutter-base-app-209d4',
    authDomain: 'flutter-base-app-209d4.firebaseapp.com',
    storageBucket: 'flutter-base-app-209d4.firebasestorage.app',
    measurementId: 'G-ZSCT425E70',
  );
}
