// Project imports:
import '../../data/models/common/country_code/country_code.dart';
import '../utils/validators/validators.dart';

class CountryCodes {
  static final List<CountryCode> _countryCodes = [
    const CountryCode(
      name: 'Jordan',
      code: 'JO',
      flag: '🇯🇴',
      dialCode: '+962',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      groupSizes: [2, 3, 4],
      mobilePrefixes: ['77', '78', '79'],
    ),
    const CountryCode(
      name: 'United States',
      code: 'US',
      flag: '🇺🇸',
      dialCode: '+1',
      minLength: 10,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      groupSizes: [3, 3, 4],
    ),
    const CountryCode(
      name: 'United Kingdom',
      code: 'GB',
      flag: '🇬🇧',
      dialCode: '+44',
      minLength: 9,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      groupSizes: [4, 6],
      mobilePrefixes: ['7'],
    ),
    const CountryCode(
      name: 'Saudi Arabia',
      code: 'SA',
      flag: '🇸🇦',
      dialCode: '+966',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      groupSizes: [2, 3, 4],
      mobilePrefixes: ['5'],
    ),
    const CountryCode(
      name: 'United Arab Emirates',
      code: 'AE',
      flag: '🇦🇪',
      dialCode: '+971',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      groupSizes: [2, 3, 4],
      mobilePrefixes: ['5'],
    ),
    const CountryCode(
      name: 'Kuwait',
      code: 'KW',
      flag: '🇰🇼',
      dialCode: '+965',
      minLength: 7,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
      groupSizes: [4, 4],
      mobilePrefixes: ['5', '6', '9'],
    ),
    const CountryCode(
      name: 'Qatar',
      code: 'QA',
      flag: '🇶🇦',
      dialCode: '+974',
      minLength: 7,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
      groupSizes: [4, 4],
      mobilePrefixes: ['3', '5', '6', '7'],
    ),
    const CountryCode(
      name: 'Bahrain',
      code: 'BH',
      flag: '🇧🇭',
      dialCode: '+973',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
      groupSizes: [4, 4],
      mobilePrefixes: ['3', '6'],
    ),
    const CountryCode(
      name: 'Oman',
      code: 'OM',
      flag: '🇴🇲',
      dialCode: '+968',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
      groupSizes: [4, 4],
      mobilePrefixes: ['7', '9'],
    ),
    const CountryCode(
      name: 'Egypt',
      code: 'EG',
      flag: '🇪🇬',
      dialCode: '+20',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      groupSizes: [3, 3, 4],
      mobilePrefixes: ['10', '11', '12', '15'],
    ),
    const CountryCode(
      name: 'Lebanon',
      code: 'LB',
      flag: '🇱🇧',
      dialCode: '+961',
      minLength: 7,
      maxLength: 8,
      mobileMinLength: 7,
      mobileMaxLength: 8,
      mobilePrefixes: ['3', '7', '8'],
    ),
    const CountryCode(
      name: 'Syria',
      code: 'SY',
      flag: '🇸🇾',
      dialCode: '+963',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['9'],
    ),
    const CountryCode(
      name: 'Iraq',
      code: 'IQ',
      flag: '🇮🇶',
      dialCode: '+964',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      groupSizes: [3, 3, 4],
      mobilePrefixes: ['7'],
    ),
    const CountryCode(
      name: 'Palestine',
      code: 'PS',
      flag: '🇵🇸',
      dialCode: '+970',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      groupSizes: [2, 3, 4],
      mobilePrefixes: ['5'],
    ),
    const CountryCode(
      name: 'Yemen',
      code: 'YE',
      flag: '🇾🇪',
      dialCode: '+967',
      minLength: 7,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['7'],
    ),
    const CountryCode(
      name: 'Libya',
      code: 'LY',
      flag: '🇱🇾',
      dialCode: '+218',
      minLength: 7,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['9'],
    ),
    const CountryCode(
      name: 'Tunisia',
      code: 'TN',
      flag: '🇹🇳',
      dialCode: '+216',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Algeria',
      code: 'DZ',
      flag: '🇩🇿',
      dialCode: '+213',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['5', '6', '7'],
    ),
    const CountryCode(
      name: 'Morocco',
      code: 'MA',
      flag: '🇲🇦',
      dialCode: '+212',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['6', '7'],
    ),
    const CountryCode(
      name: 'Sudan',
      code: 'SD',
      flag: '🇸🇩',
      dialCode: '+249',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['9'],
    ),
    const CountryCode(
      name: 'Turkey',
      code: 'TR',
      flag: '🇹🇷',
      dialCode: '+90',
      minLength: 10,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      groupSizes: [3, 3, 2, 2],
      mobilePrefixes: ['5'],
    ),
    const CountryCode(
      name: 'Iran',
      code: 'IR',
      flag: '🇮🇷',
      dialCode: '+98',
      minLength: 10,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      mobilePrefixes: ['9'],
    ),
    const CountryCode(
      name: 'Pakistan',
      code: 'PK',
      flag: '🇵🇰',
      dialCode: '+92',
      minLength: 9,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      mobilePrefixes: ['3'],
    ),
    const CountryCode(
      name: 'Afghanistan',
      code: 'AF',
      flag: '🇦🇫',
      dialCode: '+93',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['7'],
    ),
    const CountryCode(
      name: 'India',
      code: 'IN',
      flag: '🇮🇳',
      dialCode: '+91',
      minLength: 10,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      groupSizes: [5, 5],
      mobilePrefixes: ['6', '7', '8', '9'],
    ),
    const CountryCode(
      name: 'Bangladesh',
      code: 'BD',
      flag: '🇧🇩',
      dialCode: '+880',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      mobilePrefixes: ['1'],
    ),
    const CountryCode(
      name: 'Sri Lanka',
      code: 'LK',
      flag: '🇱🇰',
      dialCode: '+94',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['7'],
    ),
    const CountryCode(
      name: 'Nepal',
      code: 'NP',
      flag: '🇳🇵',
      dialCode: '+977',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      mobilePrefixes: ['9'],
    ),
    const CountryCode(
      name: 'Myanmar',
      code: 'MM',
      flag: '🇲🇲',
      dialCode: '+95',
      minLength: 7,
      maxLength: 10,
      mobileMinLength: 9,
      mobileMaxLength: 10,
    ),
    const CountryCode(
      name: 'Thailand',
      code: 'TH',
      flag: '🇹🇭',
      dialCode: '+66',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['6', '8', '9'],
    ),
    const CountryCode(
      name: 'Vietnam',
      code: 'VN',
      flag: '🇻🇳',
      dialCode: '+84',
      minLength: 9,
      maxLength: 10,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Cambodia',
      code: 'KH',
      flag: '🇰🇭',
      dialCode: '+855',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 8,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Laos',
      code: 'LA',
      flag: '🇱🇦',
      dialCode: '+856',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
    ),
    const CountryCode(
      name: 'Malaysia',
      code: 'MY',
      flag: '🇲🇾',
      dialCode: '+60',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 9,
      mobileMaxLength: 10,
      mobilePrefixes: ['1'],
    ),
    const CountryCode(
      name: 'Singapore',
      code: 'SG',
      flag: '🇸🇬',
      dialCode: '+65',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
      mobilePrefixes: ['8', '9'],
    ),
    const CountryCode(
      name: 'Indonesia',
      code: 'ID',
      flag: '🇮🇩',
      dialCode: '+62',
      minLength: 8,
      maxLength: 12,
      mobileMinLength: 9,
      mobileMaxLength: 12,
      mobilePrefixes: ['8'],
    ),
    const CountryCode(
      name: 'Philippines',
      code: 'PH',
      flag: '🇵🇭',
      dialCode: '+63',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      mobilePrefixes: ['9'],
    ),
    const CountryCode(
      name: 'China',
      code: 'CN',
      flag: '🇨🇳',
      dialCode: '+86',
      minLength: 10,
      maxLength: 11,
      mobileMinLength: 11,
      mobileMaxLength: 11,
      mobilePrefixes: ['1'],
    ),
    const CountryCode(
      name: 'Japan',
      code: 'JP',
      flag: '🇯🇵',
      dialCode: '+81',
      minLength: 9,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      mobilePrefixes: ['7', '8', '9'],
    ),
    const CountryCode(
      name: 'South Korea',
      code: 'KR',
      flag: '🇰🇷',
      dialCode: '+82',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 9,
      mobileMaxLength: 10,
      mobilePrefixes: ['1'],
    ),
    const CountryCode(
      name: 'North Korea',
      code: 'KP',
      flag: '🇰🇵',
      dialCode: '+850',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
    ),
    const CountryCode(
      name: 'Mongolia',
      code: 'MN',
      flag: '🇲🇳',
      dialCode: '+976',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Taiwan',
      code: 'TW',
      flag: '🇹🇼',
      dialCode: '+886',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Hong Kong',
      code: 'HK',
      flag: '🇭🇰',
      dialCode: '+852',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Macau',
      code: 'MO',
      flag: '🇲🇴',
      dialCode: '+853',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Canada',
      code: 'CA',
      flag: '🇨🇦',
      dialCode: '+1',
      minLength: 10,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      groupSizes: [3, 3, 4],
    ),
    const CountryCode(
      name: 'Mexico',
      code: 'MX',
      flag: '🇲🇽',
      dialCode: '+52',
      minLength: 10,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
    ),
    const CountryCode(
      name: 'Brazil',
      code: 'BR',
      flag: '🇧🇷',
      dialCode: '+55',
      minLength: 10,
      maxLength: 11,
      mobileMinLength: 11,
      mobileMaxLength: 11,
      groupSizes: [2, 5, 4],
    ),
    const CountryCode(
      name: 'Argentina',
      code: 'AR',
      flag: '🇦🇷',
      dialCode: '+54',
      minLength: 10,
      maxLength: 11,
      mobileMinLength: 10,
      mobileMaxLength: 11,
    ),
    const CountryCode(
      name: 'Chile',
      code: 'CL',
      flag: '🇨🇱',
      dialCode: '+56',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Peru',
      code: 'PE',
      flag: '🇵🇪',
      dialCode: '+51',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Colombia',
      code: 'CO',
      flag: '🇨🇴',
      dialCode: '+57',
      minLength: 10,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
    ),
    const CountryCode(
      name: 'Venezuela',
      code: 'VE',
      flag: '🇻🇪',
      dialCode: '+58',
      minLength: 10,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
    ),
    const CountryCode(
      name: 'Ecuador',
      code: 'EC',
      flag: '🇪🇨',
      dialCode: '+593',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Bolivia',
      code: 'BO',
      flag: '🇧🇴',
      dialCode: '+591',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Paraguay',
      code: 'PY',
      flag: '🇵🇾',
      dialCode: '+595',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Uruguay',
      code: 'UY',
      flag: '🇺🇾',
      dialCode: '+598',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Guyana',
      code: 'GY',
      flag: '🇬🇾',
      dialCode: '+592',
      minLength: 7,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Suriname',
      code: 'SR',
      flag: '🇸🇷',
      dialCode: '+597',
      minLength: 6,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'French Guiana',
      code: 'GF',
      flag: '🇬🇫',
      dialCode: '+594',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Germany',
      code: 'DE',
      flag: '🇩🇪',
      dialCode: '+49',
      minLength: 6,
      maxLength: 11,
      mobileMinLength: 10,
      mobileMaxLength: 11,
      mobilePrefixes: ['15', '16', '17'],
    ),
    const CountryCode(
      name: 'France',
      code: 'FR',
      flag: '🇫🇷',
      dialCode: '+33',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      groupSizes: [1, 2, 2, 2, 2],
      mobilePrefixes: ['6', '7'],
    ),
    const CountryCode(
      name: 'Italy',
      code: 'IT',
      flag: '🇮🇹',
      dialCode: '+39',
      minLength: 6,
      maxLength: 11,
      mobileMinLength: 9,
      mobileMaxLength: 10,
      mobilePrefixes: ['3'],
    ),
    const CountryCode(
      name: 'Spain',
      code: 'ES',
      flag: '🇪🇸',
      dialCode: '+34',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['6', '7'],
    ),
    const CountryCode(
      name: 'Portugal',
      code: 'PT',
      flag: '🇵🇹',
      dialCode: '+351',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['9'],
    ),
    const CountryCode(
      name: 'Netherlands',
      code: 'NL',
      flag: '🇳🇱',
      dialCode: '+31',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['6'],
    ),
    const CountryCode(
      name: 'Belgium',
      code: 'BE',
      flag: '🇧🇪',
      dialCode: '+32',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['4'],
    ),
    const CountryCode(
      name: 'Switzerland',
      code: 'CH',
      flag: '🇨🇭',
      dialCode: '+41',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['7'],
    ),
    const CountryCode(
      name: 'Austria',
      code: 'AT',
      flag: '🇦🇹',
      dialCode: '+43',
      minLength: 7,
      maxLength: 13,
      mobileMinLength: 9,
      mobileMaxLength: 13,
      mobilePrefixes: ['6'],
    ),
    const CountryCode(
      name: 'Sweden',
      code: 'SE',
      flag: '🇸🇪',
      dialCode: '+46',
      minLength: 7,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['7'],
    ),
    const CountryCode(
      name: 'Norway',
      code: 'NO',
      flag: '🇳🇴',
      dialCode: '+47',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Denmark',
      code: 'DK',
      flag: '🇩🇰',
      dialCode: '+45',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Finland',
      code: 'FI',
      flag: '🇫🇮',
      dialCode: '+358',
      minLength: 6,
      maxLength: 11,
      mobileMinLength: 9,
      mobileMaxLength: 10,
    ),
    const CountryCode(
      name: 'Iceland',
      code: 'IS',
      flag: '🇮🇸',
      dialCode: '+354',
      minLength: 7,
      maxLength: 9,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Poland',
      code: 'PL',
      flag: '🇵🇱',
      dialCode: '+48',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Czech Republic',
      code: 'CZ',
      flag: '🇨🇿',
      dialCode: '+420',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['6', '7'],
    ),
    const CountryCode(
      name: 'Slovakia',
      code: 'SK',
      flag: '🇸🇰',
      dialCode: '+421',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['9'],
    ),
    const CountryCode(
      name: 'Hungary',
      code: 'HU',
      flag: '🇭🇺',
      dialCode: '+36',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Romania',
      code: 'RO',
      flag: '🇷🇴',
      dialCode: '+40',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['7'],
    ),
    const CountryCode(
      name: 'Bulgaria',
      code: 'BG',
      flag: '🇧🇬',
      dialCode: '+359',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Croatia',
      code: 'HR',
      flag: '🇭🇷',
      dialCode: '+385',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Slovenia',
      code: 'SI',
      flag: '🇸🇮',
      dialCode: '+386',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Serbia',
      code: 'RS',
      flag: '🇷🇸',
      dialCode: '+381',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 8,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Montenegro',
      code: 'ME',
      flag: '🇲🇪',
      dialCode: '+382',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Bosnia and Herzegovina',
      code: 'BA',
      flag: '🇧🇦',
      dialCode: '+387',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'North Macedonia',
      code: 'MK',
      flag: '🇲🇰',
      dialCode: '+389',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Albania',
      code: 'AL',
      flag: '🇦🇱',
      dialCode: '+355',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Greece',
      code: 'GR',
      flag: '🇬🇷',
      dialCode: '+30',
      minLength: 10,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      mobilePrefixes: ['6'],
    ),
    const CountryCode(
      name: 'Cyprus',
      code: 'CY',
      flag: '🇨🇾',
      dialCode: '+357',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Malta',
      code: 'MT',
      flag: '🇲🇹',
      dialCode: '+356',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Ireland',
      code: 'IE',
      flag: '🇮🇪',
      dialCode: '+353',
      minLength: 7,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['8'],
    ),
    const CountryCode(
      name: 'Luxembourg',
      code: 'LU',
      flag: '🇱🇺',
      dialCode: '+352',
      minLength: 6,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Monaco',
      code: 'MC',
      flag: '🇲🇨',
      dialCode: '+377',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 8,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Liechtenstein',
      code: 'LI',
      flag: '🇱🇮',
      dialCode: '+423',
      minLength: 7,
      maxLength: 9,
      mobileMinLength: 7,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'San Marino',
      code: 'SM',
      flag: '🇸🇲',
      dialCode: '+378',
      minLength: 6,
      maxLength: 10,
      mobileMinLength: 8,
      mobileMaxLength: 10,
    ),
    const CountryCode(
      name: 'Vatican City',
      code: 'VA',
      flag: '🇻🇦',
      dialCode: '+379',
      minLength: 6,
      maxLength: 11,
      mobileMinLength: 9,
      mobileMaxLength: 10,
    ),
    const CountryCode(
      name: 'Andorra',
      code: 'AD',
      flag: '🇦🇩',
      dialCode: '+376',
      minLength: 6,
      maxLength: 9,
      mobileMinLength: 6,
      mobileMaxLength: 6,
    ),
    const CountryCode(
      name: 'Russia',
      code: 'RU',
      flag: '🇷🇺',
      dialCode: '+7',
      minLength: 10,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      groupSizes: [3, 3, 2, 2],
      mobilePrefixes: ['9'],
    ),
    const CountryCode(
      name: 'Ukraine',
      code: 'UA',
      flag: '🇺🇦',
      dialCode: '+380',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Belarus',
      code: 'BY',
      flag: '🇧🇾',
      dialCode: '+375',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Moldova',
      code: 'MD',
      flag: '🇲🇩',
      dialCode: '+373',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Estonia',
      code: 'EE',
      flag: '🇪🇪',
      dialCode: '+372',
      minLength: 7,
      maxLength: 8,
      mobileMinLength: 7,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Latvia',
      code: 'LV',
      flag: '🇱🇻',
      dialCode: '+371',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Lithuania',
      code: 'LT',
      flag: '🇱🇹',
      dialCode: '+370',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Georgia',
      code: 'GE',
      flag: '🇬🇪',
      dialCode: '+995',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Armenia',
      code: 'AM',
      flag: '🇦🇲',
      dialCode: '+374',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Azerbaijan',
      code: 'AZ',
      flag: '🇦🇿',
      dialCode: '+994',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Kazakhstan',
      code: 'KZ',
      flag: '🇰🇿',
      dialCode: '+7',
      minLength: 10,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
    ),
    const CountryCode(
      name: 'Uzbekistan',
      code: 'UZ',
      flag: '🇺🇿',
      dialCode: '+998',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Kyrgyzstan',
      code: 'KG',
      flag: '🇰🇬',
      dialCode: '+996',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Tajikistan',
      code: 'TJ',
      flag: '🇹🇯',
      dialCode: '+992',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Turkmenistan',
      code: 'TM',
      flag: '🇹🇲',
      dialCode: '+993',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Australia',
      code: 'AU',
      flag: '🇦🇺',
      dialCode: '+61',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['4'],
    ),
    const CountryCode(
      name: 'New Zealand',
      code: 'NZ',
      flag: '🇳🇿',
      dialCode: '+64',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 8,
      mobileMaxLength: 10,
      mobilePrefixes: ['2'],
    ),
    const CountryCode(
      name: 'Fiji',
      code: 'FJ',
      flag: '🇫🇯',
      dialCode: '+679',
      minLength: 7,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Papua New Guinea',
      code: 'PG',
      flag: '🇵🇬',
      dialCode: '+675',
      minLength: 7,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Solomon Islands',
      code: 'SB',
      flag: '🇸🇧',
      dialCode: '+677',
      minLength: 5,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Vanuatu',
      code: 'VU',
      flag: '🇻🇺',
      dialCode: '+678',
      minLength: 5,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'New Caledonia',
      code: 'NC',
      flag: '🇳🇨',
      dialCode: '+687',
      minLength: 6,
      maxLength: 6,
      mobileMinLength: 6,
      mobileMaxLength: 6,
    ),
    const CountryCode(
      name: 'French Polynesia',
      code: 'PF',
      flag: '🇵🇫',
      dialCode: '+689',
      minLength: 6,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Samoa',
      code: 'WS',
      flag: '🇼🇸',
      dialCode: '+685',
      minLength: 5,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Tonga',
      code: 'TO',
      flag: '🇹🇴',
      dialCode: '+676',
      minLength: 5,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Kiribati',
      code: 'KI',
      flag: '🇰🇮',
      dialCode: '+686',
      minLength: 5,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Tuvalu',
      code: 'TV',
      flag: '🇹🇻',
      dialCode: '+688',
      minLength: 5,
      maxLength: 7,
      mobileMinLength: 6,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Nauru',
      code: 'NR',
      flag: '🇳🇷',
      dialCode: '+674',
      minLength: 7,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Palau',
      code: 'PW',
      flag: '🇵🇼',
      dialCode: '+680',
      minLength: 7,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Marshall Islands',
      code: 'MH',
      flag: '🇲🇭',
      dialCode: '+692',
      minLength: 7,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Micronesia',
      code: 'FM',
      flag: '🇫🇲',
      dialCode: '+691',
      minLength: 7,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'South Africa',
      code: 'ZA',
      flag: '🇿🇦',
      dialCode: '+27',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['6', '7', '8'],
    ),
    const CountryCode(
      name: 'Nigeria',
      code: 'NG',
      flag: '🇳🇬',
      dialCode: '+234',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
      mobilePrefixes: ['7', '8', '9'],
    ),
    const CountryCode(
      name: 'Kenya',
      code: 'KE',
      flag: '🇰🇪',
      dialCode: '+254',
      minLength: 7,
      maxLength: 10,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['1', '7'],
    ),
    const CountryCode(
      name: 'Ghana',
      code: 'GH',
      flag: '🇬🇭',
      dialCode: '+233',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['2', '5'],
    ),
    const CountryCode(
      name: 'Ethiopia',
      code: 'ET',
      flag: '🇪🇹',
      dialCode: '+251',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['9'],
    ),
    const CountryCode(
      name: 'Tanzania',
      code: 'TZ',
      flag: '🇹🇿',
      dialCode: '+255',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['6', '7'],
    ),
    const CountryCode(
      name: 'Uganda',
      code: 'UG',
      flag: '🇺🇬',
      dialCode: '+256',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['7'],
    ),
    const CountryCode(
      name: 'Zimbabwe',
      code: 'ZW',
      flag: '🇿🇼',
      dialCode: '+263',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Zambia',
      code: 'ZM',
      flag: '🇿🇲',
      dialCode: '+260',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Malawi',
      code: 'MW',
      flag: '🇲🇼',
      dialCode: '+265',
      minLength: 7,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Mozambique',
      code: 'MZ',
      flag: '🇲🇿',
      dialCode: '+258',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Botswana',
      code: 'BW',
      flag: '🇧🇼',
      dialCode: '+267',
      minLength: 7,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Namibia',
      code: 'NA',
      flag: '🇳🇦',
      dialCode: '+264',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Lesotho',
      code: 'LS',
      flag: '🇱🇸',
      dialCode: '+266',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Eswatini',
      code: 'SZ',
      flag: '🇸🇿',
      dialCode: '+268',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Madagascar',
      code: 'MG',
      flag: '🇲🇬',
      dialCode: '+261',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Mauritius',
      code: 'MU',
      flag: '🇲🇺',
      dialCode: '+230',
      minLength: 7,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Seychelles',
      code: 'SC',
      flag: '🇸🇨',
      dialCode: '+248',
      minLength: 7,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Comoros',
      code: 'KM',
      flag: '🇰🇲',
      dialCode: '+269',
      minLength: 7,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Djibouti',
      code: 'DJ',
      flag: '🇩🇯',
      dialCode: '+253',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Somalia',
      code: 'SO',
      flag: '🇸🇴',
      dialCode: '+252',
      minLength: 6,
      maxLength: 9,
      mobileMinLength: 8,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Eritrea',
      code: 'ER',
      flag: '🇪🇷',
      dialCode: '+291',
      minLength: 7,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Chad',
      code: 'TD',
      flag: '🇹🇩',
      dialCode: '+235',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Central African Republic',
      code: 'CF',
      flag: '🇨🇫',
      dialCode: '+236',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Cameroon',
      code: 'CM',
      flag: '🇨🇲',
      dialCode: '+237',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Gabon',
      code: 'GA',
      flag: '🇬🇦',
      dialCode: '+241',
      minLength: 7,
      maxLength: 8,
      mobileMinLength: 7,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Congo',
      code: 'CG',
      flag: '🇨🇬',
      dialCode: '+242',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Democratic Republic of the Congo',
      code: 'CD',
      flag: '🇨🇩',
      dialCode: '+243',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Angola',
      code: 'AO',
      flag: '🇦🇴',
      dialCode: '+244',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Equatorial Guinea',
      code: 'GQ',
      flag: '🇬🇶',
      dialCode: '+240',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'São Tomé and Príncipe',
      code: 'ST',
      flag: '🇸🇹',
      dialCode: '+239',
      minLength: 7,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Cape Verde',
      code: 'CV',
      flag: '🇨🇻',
      dialCode: '+238',
      minLength: 7,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Guinea-Bissau',
      code: 'GW',
      flag: '🇬🇼',
      dialCode: '+245',
      minLength: 7,
      maxLength: 9,
      mobileMinLength: 7,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Guinea',
      code: 'GN',
      flag: '🇬🇳',
      dialCode: '+224',
      minLength: 8,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Sierra Leone',
      code: 'SL',
      flag: '🇸🇱',
      dialCode: '+232',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Liberia',
      code: 'LR',
      flag: '🇱🇷',
      dialCode: '+231',
      minLength: 7,
      maxLength: 9,
      mobileMinLength: 7,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Côte d\'Ivoire',
      code: 'CI',
      flag: '🇨🇮',
      dialCode: '+225',
      minLength: 10,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
    ),
    const CountryCode(
      name: 'Burkina Faso',
      code: 'BF',
      flag: '🇧🇫',
      dialCode: '+226',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Mali',
      code: 'ML',
      flag: '🇲🇱',
      dialCode: '+223',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Niger',
      code: 'NE',
      flag: '🇳🇪',
      dialCode: '+227',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Benin',
      code: 'BJ',
      flag: '🇧🇯',
      dialCode: '+229',
      minLength: 8,
      maxLength: 10,
      mobileMinLength: 10,
      mobileMaxLength: 10,
    ),
    const CountryCode(
      name: 'Togo',
      code: 'TG',
      flag: '🇹🇬',
      dialCode: '+228',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Senegal',
      code: 'SN',
      flag: '🇸🇳',
      dialCode: '+221',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
    ),
    const CountryCode(
      name: 'Gambia',
      code: 'GM',
      flag: '🇬🇲',
      dialCode: '+220',
      minLength: 7,
      maxLength: 7,
      mobileMinLength: 7,
      mobileMaxLength: 7,
    ),
    const CountryCode(
      name: 'Mauritania',
      code: 'MR',
      flag: '🇲🇷',
      dialCode: '+222',
      minLength: 8,
      maxLength: 8,
      mobileMinLength: 8,
      mobileMaxLength: 8,
    ),
    const CountryCode(
      name: 'Western Sahara',
      code: 'EH',
      flag: '🇪🇭',
      dialCode: '+212',
      minLength: 9,
      maxLength: 9,
      mobileMinLength: 9,
      mobileMaxLength: 9,
      mobilePrefixes: ['6', '7'],
    ),
    unknownCountryCode,
  ];

  static const CountryCode unknownCountryCode = CountryCode(
    name: 'Unknown',
    code: 'ZZ',
    flag: '🏳️',
    dialCode: '+0',
  );

  static CountryCode getCountryCodeByDialCode(String dialCode) =>
      _countryCodes.firstWhere(
        (country) => country.dialCode == dialCode,
        orElse: () => unknownCountryCode,
      );
  static CountryCode getCountryCodeByCode(String code) =>
      _countryCodes.firstWhere(
        (country) => country.code == code,
        orElse: () => unknownCountryCode,
      );
  static CountryCode getDefaultCountryCode() => _countryCodes.first;
  static CountryCode getCountryCodeByPhoneNumber(String? phoneNumber) {
    if (phoneNumber == null || phoneNumber.isEmpty) return unknownCountryCode;

    var cleanedNumber = phoneNumber.replaceAll(Validators.cleanPhoneNumber, '');

    if (!cleanedNumber.startsWith('+')) return unknownCountryCode;

    for (var dialCode in dialCodes) {
      if (cleanedNumber.startsWith(dialCode)) {
        return getCountryCodeByDialCode(dialCode);
      }
    }

    return unknownCountryCode;
  }

  static final _intlNoise = RegExp(r'[\s\-.()]');
  static final _nonDigit = RegExp(r'\D');

  /// Splits a full international number into country + NSN digits.
  /// Accepts `+962 79-123.4567` and `00962791234567` forms; longest dial
  /// code wins (`+1876` before `+1`). Null when the input isn't
  /// international, the dial code is unknown, or no digits follow it.
  static ({CountryCode country, String national})? parseInternational(
    String raw,
  ) {
    var cleaned = raw.trim().replaceAll(_intlNoise, '');
    if (cleaned.startsWith('00')) cleaned = '+${cleaned.substring(2)}';
    if (!cleaned.startsWith('+')) return null;
    final match = getCountryCodeByPhoneNumber(cleaned);
    final dial = match.dialCode;
    if (match == unknownCountryCode || dial == null) return null;
    final national = cleaned.substring(dial.length).replaceAll(_nonDigit, '');
    if (national.isEmpty) return null;
    return (country: match, national: national);
  }

  static bool isValidCountryCode(String code) =>
      _countryCodes.any((country) => country.code == code);

  static List<CountryCode> get countryCodes => _countryCodes;

  /// Returns all dial codes sorted by length (longest first) for better matching
  /// This prevents shorter codes like '+1' from matching before longer ones like '+1876'
  static List<String> get dialCodes {
    final codes = _countryCodes
        .map((country) => country.dialCode ?? '')
        .where((code) => code.isNotEmpty)
        .toSet() // Remove duplicates
        .toList();
    codes.sort(
      (a, b) => b.length.compareTo(a.length),
    ); // Sort by length descending
    return codes;
  }

  static List<String> get codes =>
      _countryCodes.map((country) => country.code).toList();
  static List<String> get flags =>
      _countryCodes.map((country) => country.flag ?? '').toList();
  static List<String> get names =>
      _countryCodes.map((country) => country.name ?? '').toList();
}
