import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';

/// One ISO-4217 currency — drives the amount field's decimal cap
/// (JOD = 3, USD = 2, JPY = 0), symbol placement and picker rows.
@immutable
class Currency {
  const Currency({
    required this.code,
    required this.symbol,
    required this.name,
    required this.nameAr,
    this.countryCode,
    this.decimalDigits = 2,
    this.symbolBeforeAmount = true,
  });

  /// ISO-4217 alpha code (`'JOD'`).
  final String code;

  /// ISO-3166 country for the flag + locale-default lookup (`'JO'`,
  /// `'EU'` for the euro). Null for multi-country currencies with no
  /// single flag (XOF / XAF / XPF / XCD).
  final String? countryCode;

  /// Display symbol (`'JD'`, `'$'`, `'€'`).
  final String symbol;

  /// English name.
  final String name;

  /// Arabic name. Deliberately INLINE, not ARB: `AmountToWords.money`
  /// takes a forced `arabic:` flag (Arabic cheque wording while the UI
  /// runs in English) and ARB lookups are bound to the loaded locale
  /// bundle — an ARB-backed name couldn't serve the cross-locale
  /// engine. Display paths still localize via [displayName].
  final String nameAr;

  /// Minor-unit digits per ISO-4217 (JOD/KWD/BHD/OMR/TND = 3, JPY/KRW
  /// = 0). The amount formatter caps typing at this.
  final int decimalDigits;

  /// `$ 49.99` vs `49.99 د.أ`.
  final bool symbolBeforeAmount;

  /// Name matching the active locale.
  String get displayName =>
      Intl.getCurrentLocale().startsWith('ar') ? nameAr : name;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Currency && other.code == code;

  @override
  int get hashCode => code.hashCode;
}

/// The currency dictionary — adopter-editable, same philosophy as
/// `CountryCodes` (lengths/prefixes for phone). Order = picker order.
class Currencies {
  Currencies._();

  static const List<Currency> all = [
    Currency(
      code: 'JOD',
      countryCode: 'JO',
      symbol: 'JD',
      name: 'Jordanian Dinar',
      nameAr: 'دينار أردني',
      decimalDigits: 3,
    ),
    Currency(
      code: 'USD',
      countryCode: 'US',
      symbol: r'$',
      name: 'US Dollar',
      nameAr: 'دولار أمريكي',
    ),
    Currency(
      code: 'EUR',
      countryCode: 'EU',
      symbol: '€',
      name: 'Euro',
      nameAr: 'يورو',
    ),
    Currency(
      code: 'GBP',
      countryCode: 'GB',
      symbol: '£',
      name: 'British Pound',
      nameAr: 'جنيه إسترليني',
    ),
    Currency(
      code: 'SAR',
      countryCode: 'SA',
      symbol: 'SR',
      name: 'Saudi Riyal',
      nameAr: 'ريال سعودي',
    ),
    Currency(
      code: 'AED',
      countryCode: 'AE',
      symbol: 'DH',
      name: 'UAE Dirham',
      nameAr: 'درهم إماراتي',
    ),
    Currency(
      code: 'KWD',
      countryCode: 'KW',
      symbol: 'KD',
      name: 'Kuwaiti Dinar',
      nameAr: 'دينار كويتي',
      decimalDigits: 3,
    ),
    Currency(
      code: 'QAR',
      countryCode: 'QA',
      symbol: 'QR',
      name: 'Qatari Riyal',
      nameAr: 'ريال قطري',
    ),
    Currency(
      code: 'BHD',
      countryCode: 'BH',
      symbol: 'BD',
      name: 'Bahraini Dinar',
      nameAr: 'دينار بحريني',
      decimalDigits: 3,
    ),
    Currency(
      code: 'OMR',
      countryCode: 'OM',
      symbol: 'RO',
      name: 'Omani Rial',
      nameAr: 'ريال عماني',
      decimalDigits: 3,
    ),
    Currency(
      code: 'EGP',
      countryCode: 'EG',
      symbol: 'E£',
      name: 'Egyptian Pound',
      nameAr: 'جنيه مصري',
    ),
    Currency(
      code: 'LBP',
      countryCode: 'LB',
      symbol: 'LL',
      name: 'Lebanese Pound',
      nameAr: 'ليرة لبنانية',
    ),
    Currency(
      code: 'IQD',
      countryCode: 'IQ',
      symbol: 'ID',
      name: 'Iraqi Dinar',
      nameAr: 'دينار عراقي',
      decimalDigits: 3,
    ),
    Currency(
      code: 'ILS',
      countryCode: 'IL',
      symbol: '₪',
      name: 'Israeli Shekel',
      nameAr: 'شيكل',
    ),
    Currency(
      code: 'TRY',
      countryCode: 'TR',
      symbol: '₺',
      name: 'Turkish Lira',
      nameAr: 'ليرة تركية',
    ),
    Currency(
      code: 'MAD',
      countryCode: 'MA',
      symbol: 'DH',
      name: 'Moroccan Dirham',
      nameAr: 'درهم مغربي',
    ),
    Currency(
      code: 'DZD',
      countryCode: 'DZ',
      symbol: 'DA',
      name: 'Algerian Dinar',
      nameAr: 'دينار جزائري',
    ),
    Currency(
      code: 'TND',
      countryCode: 'TN',
      symbol: 'DT',
      name: 'Tunisian Dinar',
      nameAr: 'دينار تونسي',
      decimalDigits: 3,
    ),
    Currency(
      code: 'LYD',
      countryCode: 'LY',
      symbol: 'LD',
      name: 'Libyan Dinar',
      nameAr: 'دينار ليبي',
      decimalDigits: 3,
    ),
    Currency(
      code: 'YER',
      countryCode: 'YE',
      symbol: 'YR',
      name: 'Yemeni Rial',
      nameAr: 'ريال يمني',
    ),
    Currency(
      code: 'SYP',
      countryCode: 'SY',
      symbol: 'SP',
      name: 'Syrian Pound',
      nameAr: 'ليرة سورية',
    ),
    Currency(
      code: 'JPY',
      countryCode: 'JP',
      symbol: '¥',
      name: 'Japanese Yen',
      nameAr: 'ين ياباني',
      decimalDigits: 0,
    ),
    Currency(
      code: 'CNY',
      countryCode: 'CN',
      symbol: '¥',
      name: 'Chinese Yuan',
      nameAr: 'يوان صيني',
    ),
    Currency(
      code: 'KRW',
      countryCode: 'KR',
      symbol: '₩',
      name: 'South Korean Won',
      nameAr: 'وون كوري',
      decimalDigits: 0,
    ),
    Currency(
      code: 'INR',
      countryCode: 'IN',
      symbol: '₹',
      name: 'Indian Rupee',
      nameAr: 'روبية هندية',
    ),
    Currency(
      code: 'PKR',
      countryCode: 'PK',
      symbol: 'Rs',
      name: 'Pakistani Rupee',
      nameAr: 'روبية باكستانية',
    ),
    Currency(
      code: 'RUB',
      countryCode: 'RU',
      symbol: '₽',
      name: 'Russian Ruble',
      nameAr: 'روبل روسي',
    ),
    Currency(
      code: 'CHF',
      countryCode: 'CH',
      symbol: 'CHF',
      name: 'Swiss Franc',
      nameAr: 'فرنك سويسري',
    ),
    Currency(
      code: 'CAD',
      countryCode: 'CA',
      symbol: r'C$',
      name: 'Canadian Dollar',
      nameAr: 'دولار كندي',
    ),
    Currency(
      code: 'AUD',
      countryCode: 'AU',
      symbol: r'A$',
      name: 'Australian Dollar',
      nameAr: 'دولار أسترالي',
    ),
    Currency(
      code: 'SEK',
      countryCode: 'SE',
      symbol: 'kr',
      name: 'Swedish Krona',
      nameAr: 'كرونة سويدية',
    ),
    Currency(
      code: 'NOK',
      countryCode: 'NO',
      symbol: 'kr',
      name: 'Norwegian Krone',
      nameAr: 'كرونة نرويجية',
    ),
    Currency(
      code: 'DKK',
      countryCode: 'DK',
      symbol: 'kr',
      name: 'Danish Krone',
      nameAr: 'كرونة دنماركية',
    ),
    Currency(
      code: 'THB',
      countryCode: 'TH',
      symbol: '฿',
      name: 'Thai Baht',
      nameAr: 'بات تايلندي',
    ),
    Currency(
      code: 'MYR',
      countryCode: 'MY',
      symbol: 'RM',
      name: 'Malaysian Ringgit',
      nameAr: 'رينغيت ماليزي',
    ),
    Currency(
      code: 'SGD',
      countryCode: 'SG',
      symbol: r'S$',
      name: 'Singapore Dollar',
      nameAr: 'دولار سنغافوري',
    ),
    Currency(
      code: 'HKD',
      countryCode: 'HK',
      symbol: r'HK$',
      name: 'Hong Kong Dollar',
      nameAr: 'دولار هونغ كونغ',
    ),
    Currency(
      code: 'IDR',
      countryCode: 'ID',
      symbol: 'Rp',
      name: 'Indonesian Rupiah',
      nameAr: 'روبية إندونيسية',
    ),
    Currency(
      code: 'PHP',
      countryCode: 'PH',
      symbol: '₱',
      name: 'Philippine Peso',
      nameAr: 'بيزو فلبيني',
    ),
    Currency(
      code: 'VND',
      countryCode: 'VN',
      symbol: '₫',
      name: 'Vietnamese Dong',
      nameAr: 'دونغ فيتنامي',
      decimalDigits: 0,
    ),
    Currency(
      code: 'BRL',
      countryCode: 'BR',
      symbol: r'R$',
      name: 'Brazilian Real',
      nameAr: 'ريال برازيلي',
    ),
    Currency(
      code: 'MXN',
      countryCode: 'MX',
      symbol: r'MX$',
      name: 'Mexican Peso',
      nameAr: 'بيزو مكسيكي',
    ),
    Currency(
      code: 'ZAR',
      countryCode: 'ZA',
      symbol: 'R',
      name: 'South African Rand',
      nameAr: 'راند جنوب أفريقي',
    ),
    Currency(
      code: 'NGN',
      countryCode: 'NG',
      symbol: '₦',
      name: 'Nigerian Naira',
      nameAr: 'نيرة نيجيرية',
    ),
    Currency(
      code: 'KES',
      countryCode: 'KE',
      symbol: 'KSh',
      name: 'Kenyan Shilling',
      nameAr: 'شلن كيني',
    ),
    Currency(
      code: 'ETB',
      countryCode: 'ET',
      symbol: 'Br',
      name: 'Ethiopian Birr',
      nameAr: 'بير إثيوبي',
    ),

    // ── Full ISO-4217 coverage (alphabetical) ─────────────────
    Currency(
      code: 'AFN',
      countryCode: 'AF',
      symbol: '؋',
      name: 'Afghan Afghani',
      nameAr: 'أفغاني أفغانستاني',
    ),
    Currency(
      code: 'ALL',
      countryCode: 'AL',
      symbol: 'L',
      name: 'Albanian Lek',
      nameAr: 'ليك ألباني',
    ),
    Currency(
      code: 'AMD',
      countryCode: 'AM',
      symbol: '֏',
      name: 'Armenian Dram',
      nameAr: 'درام أرميني',
    ),
    Currency(
      code: 'ANG',
      countryCode: 'CW',
      symbol: 'ƒ',
      name: 'Netherlands Antillean Guilder',
      nameAr: 'غيلدر أنتيلي هولندي',
    ),
    Currency(
      code: 'AOA',
      countryCode: 'AO',
      symbol: 'Kz',
      name: 'Angolan Kwanza',
      nameAr: 'كوانزا أنغولي',
    ),
    Currency(
      code: 'ARS',
      countryCode: 'AR',
      symbol: r'AR$',
      name: 'Argentine Peso',
      nameAr: 'بيزو أرجنتيني',
    ),
    Currency(
      code: 'AWG',
      countryCode: 'AW',
      symbol: 'ƒ',
      name: 'Aruban Florin',
      nameAr: 'فلورن أروبي',
    ),
    Currency(
      code: 'AZN',
      countryCode: 'AZ',
      symbol: '₼',
      name: 'Azerbaijani Manat',
      nameAr: 'مانات أذربيجاني',
    ),
    Currency(
      code: 'BAM',
      countryCode: 'BA',
      symbol: 'KM',
      name: 'Bosnian Convertible Mark',
      nameAr: 'مارك بوسني قابل للتحويل',
    ),
    Currency(
      code: 'BBD',
      countryCode: 'BB',
      symbol: r'Bds$',
      name: 'Barbadian Dollar',
      nameAr: 'دولار بربادوسي',
    ),
    Currency(
      code: 'BDT',
      countryCode: 'BD',
      symbol: '৳',
      name: 'Bangladeshi Taka',
      nameAr: 'تاكا بنغلاديشي',
    ),
    Currency(
      code: 'BGN',
      countryCode: 'BG',
      symbol: 'лв',
      name: 'Bulgarian Lev',
      nameAr: 'ليف بلغاري',
    ),
    Currency(
      code: 'BIF',
      countryCode: 'BI',
      symbol: 'FBu',
      name: 'Burundian Franc',
      nameAr: 'فرنك بوروندي',
      decimalDigits: 0,
    ),
    Currency(
      code: 'BMD',
      countryCode: 'BM',
      symbol: r'BD$',
      name: 'Bermudian Dollar',
      nameAr: 'دولار برمودي',
    ),
    Currency(
      code: 'BND',
      countryCode: 'BN',
      symbol: r'B$',
      name: 'Brunei Dollar',
      nameAr: 'دولار بروناي',
    ),
    Currency(
      code: 'BOB',
      countryCode: 'BO',
      symbol: 'Bs',
      name: 'Bolivian Boliviano',
      nameAr: 'بوليفيانو بوليفي',
    ),
    Currency(
      code: 'BSD',
      countryCode: 'BS',
      symbol: r'B$',
      name: 'Bahamian Dollar',
      nameAr: 'دولار باهامي',
    ),
    Currency(
      code: 'BTN',
      countryCode: 'BT',
      symbol: 'Nu',
      name: 'Bhutanese Ngultrum',
      nameAr: 'نغولترم بوتاني',
    ),
    Currency(
      code: 'BWP',
      countryCode: 'BW',
      symbol: 'P',
      name: 'Botswana Pula',
      nameAr: 'بولا بوتسواني',
    ),
    Currency(
      code: 'BYN',
      countryCode: 'BY',
      symbol: 'Br',
      name: 'Belarusian Ruble',
      nameAr: 'روبل بيلاروسي',
    ),
    Currency(
      code: 'BZD',
      countryCode: 'BZ',
      symbol: r'BZ$',
      name: 'Belize Dollar',
      nameAr: 'دولار بليزي',
    ),
    Currency(
      code: 'CDF',
      countryCode: 'CD',
      symbol: 'FC',
      name: 'Congolese Franc',
      nameAr: 'فرنك كونغولي',
    ),
    Currency(
      code: 'CLP',
      countryCode: 'CL',
      symbol: r'CL$',
      name: 'Chilean Peso',
      nameAr: 'بيزو تشيلي',
      decimalDigits: 0,
    ),
    Currency(
      code: 'COP',
      countryCode: 'CO',
      symbol: r'CO$',
      name: 'Colombian Peso',
      nameAr: 'بيزو كولومبي',
    ),
    Currency(
      code: 'CRC',
      countryCode: 'CR',
      symbol: '₡',
      name: 'Costa Rican Colón',
      nameAr: 'كولون كوستاريكي',
    ),
    Currency(
      code: 'CUP',
      countryCode: 'CU',
      symbol: r'$MN',
      name: 'Cuban Peso',
      nameAr: 'بيزو كوبي',
    ),
    Currency(
      code: 'CVE',
      countryCode: 'CV',
      symbol: 'Esc',
      name: 'Cape Verdean Escudo',
      nameAr: 'إسكودو الرأس الأخضر',
    ),
    Currency(
      code: 'CZK',
      countryCode: 'CZ',
      symbol: 'Kč',
      name: 'Czech Koruna',
      nameAr: 'كورونا تشيكية',
    ),
    Currency(
      code: 'DJF',
      countryCode: 'DJ',
      symbol: 'Fdj',
      name: 'Djiboutian Franc',
      nameAr: 'فرنك جيبوتي',
      decimalDigits: 0,
    ),
    Currency(
      code: 'DOP',
      countryCode: 'DO',
      symbol: r'RD$',
      name: 'Dominican Peso',
      nameAr: 'بيزو دومينيكاني',
    ),
    Currency(
      code: 'ERN',
      countryCode: 'ER',
      symbol: 'Nfk',
      name: 'Eritrean Nakfa',
      nameAr: 'ناكفا إريتري',
    ),
    Currency(
      code: 'FJD',
      countryCode: 'FJ',
      symbol: r'FJ$',
      name: 'Fijian Dollar',
      nameAr: 'دولار فيجي',
    ),
    Currency(
      code: 'FKP',
      countryCode: 'FK',
      symbol: '£',
      name: 'Falkland Islands Pound',
      nameAr: 'جنيه جزر فوكلاند',
    ),
    Currency(
      code: 'GEL',
      countryCode: 'GE',
      symbol: '₾',
      name: 'Georgian Lari',
      nameAr: 'لاري جورجي',
    ),
    Currency(
      code: 'GHS',
      countryCode: 'GH',
      symbol: '₵',
      name: 'Ghanaian Cedi',
      nameAr: 'سيدي غاني',
    ),
    Currency(
      code: 'GIP',
      countryCode: 'GI',
      symbol: '£',
      name: 'Gibraltar Pound',
      nameAr: 'جنيه جبل طارق',
    ),
    Currency(
      code: 'GMD',
      countryCode: 'GM',
      symbol: 'D',
      name: 'Gambian Dalasi',
      nameAr: 'دالاسي غامبي',
    ),
    Currency(
      code: 'GNF',
      countryCode: 'GN',
      symbol: 'FG',
      name: 'Guinean Franc',
      nameAr: 'فرنك غيني',
      decimalDigits: 0,
    ),
    Currency(
      code: 'GTQ',
      countryCode: 'GT',
      symbol: 'Q',
      name: 'Guatemalan Quetzal',
      nameAr: 'كتزال غواتيمالي',
    ),
    Currency(
      code: 'GYD',
      countryCode: 'GY',
      symbol: r'G$',
      name: 'Guyanese Dollar',
      nameAr: 'دولار غياني',
    ),
    Currency(
      code: 'HNL',
      countryCode: 'HN',
      symbol: 'L',
      name: 'Honduran Lempira',
      nameAr: 'لمبيرا هندوراسي',
    ),
    Currency(
      code: 'HTG',
      countryCode: 'HT',
      symbol: 'G',
      name: 'Haitian Gourde',
      nameAr: 'غورد هايتي',
    ),
    Currency(
      code: 'HUF',
      countryCode: 'HU',
      symbol: 'Ft',
      name: 'Hungarian Forint',
      nameAr: 'فورنت مجري',
    ),
    Currency(
      code: 'ISK',
      countryCode: 'IS',
      symbol: 'kr',
      name: 'Icelandic Króna',
      nameAr: 'كرونا آيسلندية',
      decimalDigits: 0,
    ),
    Currency(
      code: 'JMD',
      countryCode: 'JM',
      symbol: r'J$',
      name: 'Jamaican Dollar',
      nameAr: 'دولار جامايكي',
    ),
    Currency(
      code: 'KGS',
      countryCode: 'KG',
      symbol: 'с',
      name: 'Kyrgyzstani Som',
      nameAr: 'سوم قيرغيزستاني',
    ),
    Currency(
      code: 'KHR',
      countryCode: 'KH',
      symbol: '៛',
      name: 'Cambodian Riel',
      nameAr: 'ريال كمبودي',
    ),
    Currency(
      code: 'KMF',
      countryCode: 'KM',
      symbol: 'CF',
      name: 'Comorian Franc',
      nameAr: 'فرنك قمري',
      decimalDigits: 0,
    ),
    Currency(
      code: 'KPW',
      countryCode: 'KP',
      symbol: '₩',
      name: 'North Korean Won',
      nameAr: 'وون كوري شمالي',
    ),
    Currency(
      code: 'KYD',
      countryCode: 'KY',
      symbol: r'CI$',
      name: 'Cayman Islands Dollar',
      nameAr: 'دولار جزر كايمان',
    ),
    Currency(
      code: 'KZT',
      countryCode: 'KZ',
      symbol: '₸',
      name: 'Kazakhstani Tenge',
      nameAr: 'تينغ كازاخستاني',
    ),
    Currency(
      code: 'LAK',
      countryCode: 'LA',
      symbol: '₭',
      name: 'Lao Kip',
      nameAr: 'كيب لاوسي',
    ),
    Currency(
      code: 'LKR',
      countryCode: 'LK',
      symbol: 'Rs',
      name: 'Sri Lankan Rupee',
      nameAr: 'روبية سريلانكية',
    ),
    Currency(
      code: 'LRD',
      countryCode: 'LR',
      symbol: r'L$',
      name: 'Liberian Dollar',
      nameAr: 'دولار ليبيري',
    ),
    Currency(
      code: 'LSL',
      countryCode: 'LS',
      symbol: 'L',
      name: 'Lesotho Loti',
      nameAr: 'لوتي ليسوتو',
    ),
    Currency(
      code: 'MDL',
      countryCode: 'MD',
      symbol: 'L',
      name: 'Moldovan Leu',
      nameAr: 'ليو مولدوفي',
    ),
    Currency(
      code: 'MGA',
      countryCode: 'MG',
      symbol: 'Ar',
      name: 'Malagasy Ariary',
      nameAr: 'أرياري مدغشقري',
    ),
    Currency(
      code: 'MKD',
      countryCode: 'MK',
      symbol: 'ден',
      name: 'Macedonian Denar',
      nameAr: 'دينار مقدوني',
    ),
    Currency(
      code: 'MMK',
      countryCode: 'MM',
      symbol: 'K',
      name: 'Myanmar Kyat',
      nameAr: 'كيات ميانماري',
    ),
    Currency(
      code: 'MNT',
      countryCode: 'MN',
      symbol: '₮',
      name: 'Mongolian Tögrög',
      nameAr: 'توغروغ منغولي',
    ),
    Currency(
      code: 'MOP',
      countryCode: 'MO',
      symbol: r'MOP$',
      name: 'Macanese Pataca',
      nameAr: 'باتاكا ماكاوية',
    ),
    Currency(
      code: 'MRU',
      countryCode: 'MR',
      symbol: 'UM',
      name: 'Mauritanian Ouguiya',
      nameAr: 'أوقية موريتانية',
    ),
    Currency(
      code: 'MUR',
      countryCode: 'MU',
      symbol: 'Rs',
      name: 'Mauritian Rupee',
      nameAr: 'روبية موريشيوسية',
    ),
    Currency(
      code: 'MVR',
      countryCode: 'MV',
      symbol: 'Rf',
      name: 'Maldivian Rufiyaa',
      nameAr: 'روفية مالديفية',
    ),
    Currency(
      code: 'MWK',
      countryCode: 'MW',
      symbol: 'MK',
      name: 'Malawian Kwacha',
      nameAr: 'كواشا ملاوية',
    ),
    Currency(
      code: 'MZN',
      countryCode: 'MZ',
      symbol: 'MT',
      name: 'Mozambican Metical',
      nameAr: 'متكال موزمبيقي',
    ),
    Currency(
      code: 'NAD',
      countryCode: 'NA',
      symbol: r'N$',
      name: 'Namibian Dollar',
      nameAr: 'دولار ناميبي',
    ),
    Currency(
      code: 'NIO',
      countryCode: 'NI',
      symbol: r'C$',
      name: 'Nicaraguan Córdoba',
      nameAr: 'كوردوبا نيكاراغوي',
    ),
    Currency(
      code: 'NPR',
      countryCode: 'NP',
      symbol: 'Rs',
      name: 'Nepalese Rupee',
      nameAr: 'روبية نيبالية',
    ),
    Currency(
      code: 'NZD',
      countryCode: 'NZ',
      symbol: r'NZ$',
      name: 'New Zealand Dollar',
      nameAr: 'دولار نيوزيلندي',
    ),
    Currency(
      code: 'PAB',
      countryCode: 'PA',
      symbol: 'B/',
      name: 'Panamanian Balboa',
      nameAr: 'بالبوا بنمي',
    ),
    Currency(
      code: 'PEN',
      countryCode: 'PE',
      symbol: 'S/',
      name: 'Peruvian Sol',
      nameAr: 'سول بيروفي',
    ),
    Currency(
      code: 'PGK',
      countryCode: 'PG',
      symbol: 'K',
      name: 'Papua New Guinean Kina',
      nameAr: 'كينا بابوا غينيا الجديدة',
    ),
    Currency(
      code: 'PLN',
      countryCode: 'PL',
      symbol: 'zł',
      name: 'Polish Złoty',
      nameAr: 'زلوتي بولندي',
    ),
    Currency(
      code: 'PYG',
      countryCode: 'PY',
      symbol: '₲',
      name: 'Paraguayan Guaraní',
      nameAr: 'غواراني باراغوايي',
      decimalDigits: 0,
    ),
    Currency(
      code: 'RON',
      countryCode: 'RO',
      symbol: 'lei',
      name: 'Romanian Leu',
      nameAr: 'ليو روماني',
    ),
    Currency(
      code: 'RSD',
      countryCode: 'RS',
      symbol: 'дин',
      name: 'Serbian Dinar',
      nameAr: 'دينار صربي',
    ),
    Currency(
      code: 'RWF',
      countryCode: 'RW',
      symbol: 'FRw',
      name: 'Rwandan Franc',
      nameAr: 'فرنك رواندي',
      decimalDigits: 0,
    ),
    Currency(
      code: 'SBD',
      countryCode: 'SB',
      symbol: r'SI$',
      name: 'Solomon Islands Dollar',
      nameAr: 'دولار جزر سليمان',
    ),
    Currency(
      code: 'SCR',
      countryCode: 'SC',
      symbol: 'Rs',
      name: 'Seychellois Rupee',
      nameAr: 'روبية سيشلية',
    ),
    Currency(
      code: 'SDG',
      countryCode: 'SD',
      symbol: 'SDG',
      name: 'Sudanese Pound',
      nameAr: 'جنيه سوداني',
    ),
    Currency(
      code: 'SHP',
      countryCode: 'SH',
      symbol: '£',
      name: 'Saint Helena Pound',
      nameAr: 'جنيه سانت هيلينا',
    ),
    Currency(
      code: 'SLE',
      countryCode: 'SL',
      symbol: 'Le',
      name: 'Sierra Leonean Leone',
      nameAr: 'ليون سيراليوني',
    ),
    Currency(
      code: 'SOS',
      countryCode: 'SO',
      symbol: 'Sh',
      name: 'Somali Shilling',
      nameAr: 'شلن صومالي',
    ),
    Currency(
      code: 'SRD',
      countryCode: 'SR',
      symbol: r'Sr$',
      name: 'Surinamese Dollar',
      nameAr: 'دولار سورينامي',
    ),
    Currency(
      code: 'SSP',
      countryCode: 'SS',
      symbol: 'SSP',
      name: 'South Sudanese Pound',
      nameAr: 'جنيه جنوب السودان',
    ),
    Currency(
      code: 'STN',
      countryCode: 'ST',
      symbol: 'Db',
      name: 'São Tomé Dobra',
      nameAr: 'دوبرا ساو تومي',
    ),
    Currency(
      code: 'SZL',
      countryCode: 'SZ',
      symbol: 'E',
      name: 'Swazi Lilangeni',
      nameAr: 'ليلانغيني سوازيلندي',
    ),
    Currency(
      code: 'TJS',
      countryCode: 'TJ',
      symbol: 'SM',
      name: 'Tajikistani Somoni',
      nameAr: 'سوموني طاجيكي',
    ),
    Currency(
      code: 'TMT',
      countryCode: 'TM',
      symbol: 'm',
      name: 'Turkmenistani Manat',
      nameAr: 'مانات تركمانستاني',
    ),
    Currency(
      code: 'TOP',
      countryCode: 'TO',
      symbol: r'T$',
      name: 'Tongan Paʻanga',
      nameAr: 'بانغا تونغية',
    ),
    Currency(
      code: 'TTD',
      countryCode: 'TT',
      symbol: r'TT$',
      name: 'Trinidad and Tobago Dollar',
      nameAr: 'دولار ترينيداد وتوباغو',
    ),
    Currency(
      code: 'TWD',
      countryCode: 'TW',
      symbol: r'NT$',
      name: 'New Taiwan Dollar',
      nameAr: 'دولار تايواني جديد',
    ),
    Currency(
      code: 'TZS',
      countryCode: 'TZ',
      symbol: 'Sh',
      name: 'Tanzanian Shilling',
      nameAr: 'شلن تنزاني',
    ),
    Currency(
      code: 'UAH',
      countryCode: 'UA',
      symbol: '₴',
      name: 'Ukrainian Hryvnia',
      nameAr: 'هريفنيا أوكرانية',
    ),
    Currency(
      code: 'UGX',
      countryCode: 'UG',
      symbol: 'Sh',
      name: 'Ugandan Shilling',
      nameAr: 'شلن أوغندي',
      decimalDigits: 0,
    ),
    Currency(
      code: 'UYU',
      countryCode: 'UY',
      symbol: r'$U',
      name: 'Uruguayan Peso',
      nameAr: 'بيزو أوروغوايي',
    ),
    Currency(
      code: 'UZS',
      countryCode: 'UZ',
      symbol: 'сум',
      name: 'Uzbekistani Som',
      nameAr: 'سوم أوزبكي',
    ),
    Currency(
      code: 'VES',
      countryCode: 'VE',
      symbol: 'Bs',
      name: 'Venezuelan Bolívar',
      nameAr: 'بوليفار فنزويلي',
    ),
    Currency(
      code: 'VUV',
      countryCode: 'VU',
      symbol: 'Vt',
      name: 'Vanuatu Vatu',
      nameAr: 'فاتو فانواتي',
      decimalDigits: 0,
    ),
    Currency(
      code: 'WST',
      countryCode: 'WS',
      symbol: 'T',
      name: 'Samoan Tala',
      nameAr: 'تالا ساموية',
    ),
    Currency(
      code: 'XAF',
      symbol: 'FCFA',
      name: 'Central African CFA Franc',
      nameAr: 'فرنك وسط أفريقي',
      decimalDigits: 0,
    ),
    Currency(
      code: 'XCD',
      symbol: r'EC$',
      name: 'East Caribbean Dollar',
      nameAr: 'دولار شرق الكاريبي',
    ),
    Currency(
      code: 'XOF',
      symbol: 'CFA',
      name: 'West African CFA Franc',
      nameAr: 'فرنك غرب أفريقي',
      decimalDigits: 0,
    ),
    Currency(
      code: 'XPF',
      symbol: '₣',
      name: 'CFP Franc',
      nameAr: 'فرنك المحيط الهادئ',
      decimalDigits: 0,
    ),
    Currency(
      code: 'ZMW',
      countryCode: 'ZM',
      symbol: 'ZK',
      name: 'Zambian Kwacha',
      nameAr: 'كواشا زامبية',
    ),
    Currency(
      code: 'ZWL',
      countryCode: 'ZW',
      symbol: r'Z$',
      name: 'Zimbabwean Dollar',
      nameAr: 'دولار زيمبابوي',
    ),
  ];

  /// Null when [code] isn't in the dictionary.
  static Currency? byCode(String code) {
    final upper = code.toUpperCase();
    for (final c in all) {
      if (c.code == upper) return c;
    }
    return null;
  }

  /// Eurozone members — their region locale maps to EUR even though the
  /// euro's own [Currency.countryCode] is `'EU'`.
  static const _eurozone = {
    'AT',
    'BE',
    'CY',
    'DE',
    'EE',
    'ES',
    'FI',
    'FR',
    'GR',
    'HR',
    'IE',
    'IT',
    'LT',
    'LU',
    'LV',
    'MC',
    'MT',
    'NL',
    'PT',
    'SI',
    'SK',
  };

  /// The currency of an ISO-3166 country (`'JO'` → JOD, `'DE'` → EUR).
  /// Null when unknown — callers fall back to [defaultCurrency].
  static Currency? byCountry(String countryIso) {
    final upper = countryIso.toUpperCase();
    if (_eurozone.contains(upper)) return byCode('EUR');
    for (final c in all) {
      if (c.countryCode == upper) return c;
    }
    return null;
  }

  /// Template default — adopters change per market.
  static Currency get defaultCurrency => all.first;
}
